ktor:
    application:
        modules:
            - com.smilegate.ApplicationKt.module
    deployment:
        port: 8080
        host: 0.0.0.0
postgres:
  url: ${POSTGRES_URL:jdbc:postgresql://localhost:5432/statdb}
  user: ${POSTGRES_USER:statuser}
  password: ${POSTGRES_PASSWORD:statpass}